# Setup
title:        Optimizing Food Inspections in Chicago 
tagline:      A Final Project for CS109a at Harvard University
baseurl:      "/foodinspections"
paginate:     2
future: true

# About/contact
authors:
  - name:       Luke Farewell
    url:        http://github.com/lfarewell
  - name:       Jake Gober
    url:        http://github.com/jgober96
  - name:       Samuel Green
    url:        http://sa.muel.green
  - name:       Jeremy Welborn
    url:        http://github.com/jerwelborn
  - name:       Intern
    url:        http://endless.horse
advisor:
  name:         Taylor Names
  url:          https://github.com/tnames

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown